const { DatabaseSync } = require('node:sqlite');
const d = new DatabaseSync('podcasts/llm-podcast-generator-review/generated/execution/ai_jobs.sqlite');
const rows = d.prepare("SELECT job_id, source_record_id, status, attempt_count, error_code, error_message, model, updated_at, completed_at FROM ai_jobs WHERE source_record_id LIKE 'cc-05%' ORDER BY updated_at DESC").all();
for (const r of rows) console.log(r);
console.log('--- applied marker check ---');
const fs = require('fs');
const p = 'podcasts/llm-podcast-generator-review/generated/execution/applied/cc-05-make-your-mark.candidate.json';
console.log('exists:', fs.existsSync(p));
console.log('--- live script check ---');
console.log('challenges:', fs.existsSync('podcasts/scripts/challenges/cc-05-make-your-mark.txt'));
